# Application
spring.application.name=etl-importer

# Virtual Threads
spring.threads.virtual.enabled=true

# JPA / Hibernate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Spring Batch
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always
