CREATE TABLE sale
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

    sale_date      DATE NOT NULL,
    customer_id    BIGINT,
    customer_name  VARCHAR(255) NOT NULL,
    product_id     VARCHAR(255),
    product_name   VARCHAR(255) NOT NULL,
    category       VARCHAR(255) NOT NULL,
    quantity       INTEGER,
    unit_price     NUMERIC(15,2),
    total_price    NUMERIC(15,2),
    payment_method VARCHAR(255) NOT NULL,
    status         VARCHAR(255) NOT NULL,
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_sale PRIMARY KEY (id)
);

