CREATE TABLE import_execution
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    execution_id    BIGINT NOT NULL,
    started_date    TIMESTAMP WITHOUT TIME ZONE,
    finished_date   TIMESTAMP WITHOUT TIME ZONE,
    status          VARCHAR(255),
    total_line      BIGINT,
    processed_lines BIGINT,
    success_lines   BIGINT,
    error_lines     BIGINT,
    duration        BIGINT,
    CONSTRAINT pk_importexecution PRIMARY KEY (id)
);