CREATE TABLE import_error
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    execution_id  BIGINT NOT NULL,
    line_number   BIGINT,
    error_message TEXT,
    raw_data      TEXT,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_importerror PRIMARY KEY (id)
);

ALTER TABLE import_error
    ADD CONSTRAINT fk_execution
        FOREIGN KEY (execution_id)
            REFERENCES import_execution(id);